package com.casestudy.skilltracker.employee.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.*;
import org.springframework.data.annotation.Id;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

@Setter
@Getter
@NoArgsConstructor
@ToString
@DynamoDBTable(tableName = "AssociateProfile")
public class AssociateProfile implements Serializable {

    static final long serialVersionUID = 1L;
    @DynamoDBAutoGeneratedKey
    private String userId;
    @Id
    @DynamoDBHashKey
    private String associateId;
    @DynamoDBAttribute
    private String name;
    private String email;
    @DynamoDBAttribute
    private String mobile;
    @DynamoDBAttribute
    private List<Skill> skills;
    @JsonIgnore
    @DynamoDBAttribute
    @DynamoDBAutoGeneratedTimestamp
    private Date lastModifiedDate;
}
